L1-Q1: Let ($B$) be a ($4 \times 4 $) matrix to which we apply the following operations:
1. double column 1,
2. halve row 3,
3. add row 3 to row 1,
4. interchange columns 1 and 4,
5. subtract row 2 from each of the other rows,
6. replace column 4 by column 3,
7. delete column 1 (so that the column dimension is reduced by 1).

(a) Write the result as a product of eight matrices.

(b) Write it again as a product ($ABC$) (same ($B$)) of three matrices.

In [7]:
import torch
B = torch.range(1, 16).reshape(4, 4)
e1 = torch.tensor([[2, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1],], dtype=B.dtype)
e2 = torch.tensor([[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 0.5, 0], [0, 0, 0, 1],], dtype=B.dtype)
e3 = torch.tensor([[1, 0, 1, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1],], dtype=B.dtype)
e4 = torch.tensor([[0, 0, 0, 1], [0, 1, 0, 0], [0, 0, 1, 0], [1, 0, 0, 0],], dtype=B.dtype)
e5 = torch.tensor([[1, -1, 0, 0], [0, 1, 0, 0], [0, -1, 1, 0], [0, -1, 0, 1]], dtype=B.dtype)
e6 = torch.tensor([[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 0, 0], [0, 0, 1, 1]], dtype=B.dtype)
e7 = torch.tensor([[0, 0, 0], [1, 0, 0], [0, 1, 0], [0, 0, 1]], dtype=B.dtype)

/tmp/ipykernel_1674979/1148368369.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  B = torch.range(1, 16).reshape(4, 4)


In [8]:
ans1 = e5 @ e3 @ e2 @ B @ e1 @ e4 @ e6 @ e7
ans1

tensor([[ 1.,  1.,  1.],
        [ 6., 10., 10.],
        [-1., -1., -1.],
        [ 8., 16., 16.]])

In [9]:
A = e5 @ e3 @ e2
C = e1 @ e4 @ e6 @ e7
A, C, A @ B @ C == ans1

(tensor([[ 1.0000, -1.0000,  0.5000,  0.0000],
         [ 0.0000,  1.0000,  0.0000,  0.0000],
         [ 0.0000, -1.0000,  0.5000,  0.0000],
         [ 0.0000, -1.0000,  0.0000,  1.0000]]),
 tensor([[0., 2., 2.],
         [1., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]),
 tensor([[True, True, True],
         [True, True, True],
         [True, True, True],
         [True, True, True]]))

总结：e在前，则其行对B的行起作用；e在后，则其列对B的列起作用；

---

L1-Q2: Suppose masses $m_1,m_2,m_3,m_4$ are located at positions $x_1,x_2,x_3,x_4$ in a line and connected by springs with spring constants $k_{12},k_{23},k_{34}$ whose natural lengths of extension are $l_{12},l_{23},l_{34}$. Let $f_1,f_2,f_3,f_4$ denote the rightward forces on the masses, $\mathrm{e.g.},f_1=k_{12}(x_2-x_1-l_{12}).$

(a) Write the $4\times 4$ matrix equation relating the column vectors $f$ and $x$. Let $K$ denote the matrix in this equation.

(b) What are the dimensions of the entries of $K$ in the physics sense ($\mathrm{e.g.}$, mass times time, distance divided by mass, $\mathrm{etc.}$)?

(c) What are the dimensions of $\mathrm{det}(K)$, again in the physics sense?

(d) Suppose $K$ is given numerical values based on the units meters, kilograms, and seconds. Now the system is rewritten with a matrix $K'$ based on centimeters, grams, and seconds. What is the relationship of $K'$ to $K$? What is the relationship of $\mathrm{det}(K')$ to $\mathrm{det}(K)$?